### ISSUE TITLE
scss transpiling 

### ISSUE THREAD

**Issue by greg0x** [NathanWalker/template-nativescript-nx#6]
Hi

I was trying to use component scss when realized that it does not compile to css. (I was using the _tabs.component.scss tabs.component.ios.scss tabs.component.android.scss pattern from the tabbar example.)

What I found is that the npm run css.generate gave me an error 
```
$ npm run css.generate

> @ css.generate /Users/puffancs/Dev/ella/apps/ella-mobile
> node -e 'require("./node_modules/nativescript-dev-sass/lib/converter.js").convert(console, ".");'

Found peer node-sass
Trace: /usr/local/Cellar/node/8.9.1/bin/node /Users/puffancs/Dev/ella/apps/ella-mobile/node_modules/node-sass/bin/node-sass app --output app --output-style compressed -q --follow --importer /Users/puffancs/Dev/ella/apps/ella-mobile/node_modules/nativescript-dev-sass/lib/importer.js
    at /Users/puffancs/Dev/ella/apps/ella-mobile/node_modules/nativescript-dev-sass/lib/converter.js:38:16
    at new Promise (<anonymous>)
    at Object.convert (/Users/puffancs/Dev/ella/apps/ella-mobile/node_modules/nativescript-dev-sass/lib/converter.js:10:12)
    at [eval]:1:66
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:635:30)
    at evalScript (bootstrap_node.js:462:27)
    at startup (bootstrap_node.js:163:9)
```

but when I replaced the npm script in package.json with the actual command it started to work.

I hope this helps. 

(Tried to debug what went wrong but could not find out :( )

Thx for the template, I do like that I can work with nx and ns with ng :)

**Comment by greg0x** [comment]
ohhh the mighty rubber duck effect ... 

I just needed an npm run reset. Don't know what went wrong but took me a while to realize.
