### ISSUE TITLE
Webpack Error on Clean Template

### ISSUE THREAD

**Issue by breningham** [NathanWalker/template-nativescript-nx#8]
Hi Again, Been playing around with Nx + Nativescript and i've come across an issue, Webpack does not work by default (clean run)

Just after creating the application, i ran `tns run android --bundle` and got the following error :

```(javascript)
Error: Cannot find module 'nativescript-drop-down/uglify-mangle-excludes'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/bingham/Projects/Cityverve/buzzin-events/apps/mobile/webpack.config.js:13:32)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at requireConfig (/Users/bingham/Projects/Cityverve/buzzin-events/apps/mobile/node_modules/webpack/bin/convert-argv.js:97:18)
    at /Users/bingham/Projects/Cityverve/buzzin-events/apps/mobile/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/bingham/Projects/Cityverve/buzzin-events/apps/mobile/node_modules/webpack/bin/convert-argv.js:102:15)
```

Installing the nativescript-drop-down plugin resolves this issue, which makes me believe this is residual code, and was included as a mistake?

**Comment by NathanWalker** [comment]
Hi @breningham thank you for reporting this! Indeed it was. Just pushed up with that removed. Instead of installing that plugin (if you are not using it) you can remove the lines shown in this changeset instead:
https://github.com/NathanWalker/template-nativescript-nx/commit/e09724a6ec456b7f1aeccdf8855e809153b37241
